spring:
  config:
    activate:
      on-profile: dev

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: INFO
    com.skuri.skuri_backend: INFO

app:
  openapi:
    enabled: ${OPENAPI_ENABLED:true}

springdoc:
  api-docs:
    enabled: ${OPENAPI_ENABLED:true}
  swagger-ui:
    enabled: ${OPENAPI_ENABLED:true}

scalar:
  enabled: ${OPENAPI_ENABLED:true}
